### ISSUE TITLE
Need a persistent efs volume for storing Flink metadata

### ISSUE THREAD

**Issue by thodson-usgs** [pangeo-forge/pangeo-forge-cloud-federation#17]
To recover from job-manager failures, Flink needs a persistent file system for storing [job metadata](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/ha/kubernetes_ha/). This could be s3 or efs. Of those two, I have a slight preference for the latter, because USGS uses sessions, so the cluster might lose s3 access during the course of a long job.

I'm looking into how to add a persistent volume to our k8 deployment but keep finding myself down Medium rabbit holes.

**Comment by yuvipanda** [comment]
@thodson-usgs https://github.com/pangeo-forge/pangeo-forge-cloud-federation/pull/6 sets up an EFS that can be consumed this way! Maybe you can work with @ranchodeluxe on that?

**Comment by thodson-usgs** [comment]
Sure, I'll start rebasing that branch onto main

**Comment by ranchodeluxe** [comment]
@thodson-usgs: since that other PR merged do we still need this one? Or maybe a version of it?

**Comment by thodson-usgs** [comment]
Sure. I think we can close this.
